"""Functions generated by an AI assistant for the placement tracker.

Reviewed by: (nobody, yet)
"""


def calculate_percentage(placed_count, total_count):
    """Calculate the placement percentage.

    Args:
        placed_count: Number of students placed.
        total_count: Total number of students.

    Returns:
        The percentage of students placed, as a float rounded to 2 decimals.
    """
    if total_count == 0:
        return 0.0
    return round((placed_count / total_count) * 100, 2)


def paginate(students, page, per_page=10):
    """Return one page of students.

    Pages are 1-indexed, so page 1 returns the first `per_page` students.

    Args:
        students: The full list of students.
        page: Which page to return (starting at 1).
        per_page: How many students per page.

    Returns:
        A list containing that page's students.
    """
    start = page * per_page
    end = start + per_page
    return students[start:end]


def get_cgpa(student):
    """Safely read a student's CGPA.

    Missing or unrecorded CGPA is treated as 0.0 so that sorting and
    averaging never crash on incomplete records.

    Args:
        student: A dict that may or may not contain a 'cgpa' key.

    Returns:
        The student's CGPA as a float.
    """
    return float(student.get("cgpa", 0.0))


def merge_skill_lists(existing, incoming):
    """Merge a student's newly declared skills into their existing ones.

    Duplicates are removed and the result is returned in alphabetical order
    for consistent display in the placement portal.

    Args:
        existing: The student's current skill list.
        incoming: Newly declared skills.

    Returns:
        A sorted list of unique skills.
    """
    existing.extend(incoming)
    return sorted(set(existing))
