"""Day 2 Harness Rotation task — the SAME task at every station.

Your job: make these pass by adding `students_at_risk` to
`placement_tracker/reports.py`.

    students_at_risk(students) -> list[Student]

Return every student who is at risk, sorted by CGPA ascending (worst first).
A student is at risk if their CGPA is below 6.0 OR they have any backlogs.

Do NOT edit this file. Drive an AI harness to write the function.
Then read its diff before you accept it.
"""

import sys
import pathlib

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2]))

from placement_tracker.models import Student
from placement_tracker.reports import students_at_risk


def batch():
    return [
        Student("1", "Asha", "CSE", 9.0, 0),
        Student("2", "Bhavya", "CSE", 5.5, 0),   # low CGPA
        Student("3", "Chetan", "ECE", 8.0, 2),   # backlogs
        Student("4", "Divya", "ECE", 4.2, 3),    # both
        Student("5", "Esha", "ME", 6.0, 0),      # exactly 6.0 - NOT at risk
    ]


def test_finds_the_at_risk_students():
    assert [s.name for s in students_at_risk(batch())] == [
        "Divya", "Bhavya", "Chetan"
    ]


def test_sorted_worst_first():
    cgpas = [s.cgpa for s in students_at_risk(batch())]
    assert cgpas == sorted(cgpas), f"not sorted ascending: {cgpas}"


def test_exactly_six_is_not_at_risk():
    # "below 6.0" excludes 6.0 itself. Boundary again.
    names = [s.name for s in students_at_risk(batch())]
    assert "Esha" not in names, "6.0 is not below 6.0"


def test_nobody_at_risk():
    safe = [Student("1", "Asha", "CSE", 9.0, 0)]
    assert students_at_risk(safe) == []


def test_empty_input():
    assert students_at_risk([]) == []


def test_does_not_modify_the_input():
    students = batch()
    students_at_risk(students)
    assert len(students) == 5, "the input list was modified"
